
# POST http://localhost:4000/api/auth/signup
# Content-Type: application/json

# {
#   "firstName":"pranit",
#   "lastName":"patil",
#   "email":"pranit.work.31112@gmail.com",
#   "password":"pranit123*"
# }

# POST http://localhost:4000/api/auth/sendmail
# Content-Type: application/json

# {
#   "email":"pranit.work.3112@gmail.com"
# }

# POST http://localhost:4000/api/auth/verifyotp
# Content-Type: application/json

# {
#   "email":"pranit.work.3112@gmail.com",
#   "userOtp":"154299"
# }

# POST http://localhost:4000/api/auth/change-password
# Content-Type: application/json

# {
#   "email":"pranit.work.31112@gmail.com",
#   "current_password":"Test123*",
#   "new_password":"pranit123**"
# }

