
# POST http://localhost:4000/api/auth/sendmail
# Content-Type: application/json

# {
#   "email":"pranit.work.3112@gmail.com"
# }

POST http://localhost:4000/api/auth/verifyotp
Content-Type: application/json

{
  "email":"pranit.work.3112@gmail.com",
  "userOtp":"154299"
}

